apiVersion: v1
kind: Namespace
metadata:
  name: fan-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fan-controller
  namespace: fan-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fan-controller
  template:
    metadata:
      labels:
        app: fan-controller
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      terminationGracePeriodSeconds: 10
      containers:
        - name: fan-controller
          image: ghcr.io/aderesh/raspi-k8s-fan-controller:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 36637
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-sys
              mountPath: /sys
            - name: gpio-memory
              mountPath: /dev/gpiomem
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: gpio-memory
          hostPath:
            path: /dev/gpiomem
            type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: fan-controller
  namespace: fan-controller
spec:
  selector:
    app: fan-controller
  ports:
    - name: http
      port: 36637
      targetPort: http